import {
  Utensils, Wine, Sparkles, Cookie, Droplets, Archive, Heart, Pill,
  Milk, Leaf, Candy, Coffee, UtensilsCrossed, PawPrint, Nut, Croissant,
  Egg, Beef, Wheat, Snowflake, IceCream, Fish, Gift, ShoppingBag, Tag, Package,
  Shirt, Gem, Laptop, Smartphone, Headphones, Tv, Wrench, Hammer, Zap, Car,
  Home, Armchair, Building2, Store, Briefcase, Camera, Scissors, Stethoscope,
  Dumbbell, Bike, BookOpen, GraduationCap, Printer, Pencil, Music, Palette,
  Flame, Trees, Sun, Pen,
} from 'lucide-react';

export const CATEGORY_ICON_MAP = [
  { keys: ['bebida sin alcohol'], Icon: Milk },
  { keys: ['infusion', 'infusión', 'mate', 'te ', 'té '], Icon: Coffee },
  { keys: ['bebida'], Icon: Wine },
  { keys: ['alimento'], Icon: Utensils },
  { keys: ['limpieza'], Icon: Sparkles },
  { keys: ['snack'], Icon: Cookie },
  { keys: ['galletita'], Icon: Cookie },
  { keys: ['aceite', 'vinagre'], Icon: Droplets },
  { keys: ['conserva'], Icon: Archive },
  { keys: ['cuidado'], Icon: Heart },
  { keys: ['farmacia'], Icon: Pill },
  { keys: ['condimento', 'aderezo'], Icon: Leaf },
  { keys: ['chocolate', 'golosina'], Icon: Candy },
  { keys: ['fiambre', 'queso'], Icon: UtensilsCrossed },
  { keys: ['mascota'], Icon: PawPrint },
  { keys: ['fruto', 'seco', 'nuez'], Icon: Nut },
  { keys: ['panadería', 'panaderia', 'almacén', 'almacen', 'bazar', 'hogar'], Icon: Croissant },
  { keys: ['huevo'], Icon: Egg },
  { keys: ['carne'], Icon: Beef },
  { keys: ['cereal', 'harina'], Icon: Wheat },
  { keys: ['congelado'], Icon: Snowflake },
  { keys: ['dulce', 'postre', 'mermelada', 'helado'], Icon: IceCream },
  { keys: ['pescado'], Icon: Fish },
  { keys: ['ropa', 'indumentaria', 'vestimenta', 'calzado'], Icon: Shirt },
  { keys: ['joyería', 'joyeria', 'bijouterie', 'accesorio'], Icon: Gem },
  { keys: ['computación', 'computacion', 'laptop', 'notebook'], Icon: Laptop },
  { keys: ['celular', 'telefono', 'teléfono', 'smartphone'], Icon: Smartphone },
  { keys: ['audio', 'auricular', 'sonido'], Icon: Headphones },
  { keys: ['electrónica', 'electronica', 'televisor', 'tv'], Icon: Tv },
  { keys: ['herramienta', 'ferretería', 'ferreteria'], Icon: Wrench },
  { keys: ['construcción', 'construccion', 'material'], Icon: Hammer },
  { keys: ['electricidad', 'eléctrico', 'electrico', 'luz'], Icon: Zap },
  { keys: ['automotor', 'auto', 'vehiculo', 'vehículo', 'repuesto'], Icon: Car },
  { keys: ['mueble', 'furniture', 'decoración', 'decoracion'], Icon: Armchair },
  { keys: ['inmueble', 'propiedad', 'oficina'], Icon: Building2 },
  { keys: ['comercio', 'negocio', 'tienda'], Icon: Store },
  { keys: ['servicio', 'profesional', 'empresa'], Icon: Briefcase },
  { keys: ['fotografía', 'fotografia', 'foto', 'imagen'], Icon: Camera },
  { keys: ['peluquería', 'peluqueria', 'belleza', 'estetica', 'estética'], Icon: Scissors },
  { keys: ['salud', 'médico', 'medico', 'clínica', 'clinica'], Icon: Stethoscope },
  { keys: ['deporte', 'fitness', 'gym', 'gimnasio'], Icon: Dumbbell },
  { keys: ['ciclismo', 'bicicleta', 'bike'], Icon: Bike },
  { keys: ['libro', 'librería', 'libreria'], Icon: BookOpen },
  { keys: ['educación', 'educacion', 'escuela', 'curso'], Icon: GraduationCap },
  { keys: ['papelería', 'papeleria', 'insumo'], Icon: Printer },
  { keys: ['escritura', 'lapicera', 'lápiz', 'lapiz'], Icon: Pencil },
  { keys: ['música', 'musica', 'instrumento'], Icon: Music },
  { keys: ['arte', 'pintura', 'manualidad'], Icon: Palette },
  { keys: ['combustible', 'gas', 'llama'], Icon: Flame },
  { keys: ['jardín', 'jardin', 'planta', 'vivero'], Icon: Trees },
  { keys: ['exterior', 'solar', 'iluminación', 'iluminacion'], Icon: Sun },
  { keys: ['papelería', 'librería', 'articulo'], Icon: Pen },
  { keys: ['general'], Icon: Tag },
];

export const ICON_OPTIONS = [
  // Fila 1: Alimentos y bebidas
  { key: 'Utensils', Icon: Utensils, label: 'Alimentos' },
  { key: 'Wine', Icon: Wine, label: 'Bebidas' },
  { key: 'Milk', Icon: Milk, label: 'Lácteos' },
  { key: 'Coffee', Icon: Coffee, label: 'Infusiones' },
  { key: 'Cookie', Icon: Cookie, label: 'Galletitas' },
  { key: 'Candy', Icon: Candy, label: 'Golosinas' },
  { key: 'IceCream', Icon: IceCream, label: 'Dulces' },
  { key: 'Croissant', Icon: Croissant, label: 'Panadería' },
  { key: 'Beef', Icon: Beef, label: 'Carnes' },
  { key: 'Fish', Icon: Fish, label: 'Pescados' },
  { key: 'Egg', Icon: Egg, label: 'Huevos' },
  { key: 'Wheat', Icon: Wheat, label: 'Cereales' },
  { key: 'Leaf', Icon: Leaf, label: 'Condimentos' },
  { key: 'Nut', Icon: Nut, label: 'Frutos Secos' },
  // Fila 2: Limpieza, hogar y varios
  { key: 'Droplets', Icon: Droplets, label: 'Aceites' },
  { key: 'Snowflake', Icon: Snowflake, label: 'Congelados' },
  { key: 'Archive', Icon: Archive, label: 'Conservas' },
  { key: 'Sparkles', Icon: Sparkles, label: 'Limpieza' },
  { key: 'Heart', Icon: Heart, label: 'Cuidado Personal' },
  { key: 'Pill', Icon: Pill, label: 'Farmacia' },
  { key: 'PawPrint', Icon: PawPrint, label: 'Mascotas' },
  { key: 'UtensilsCrossed', Icon: UtensilsCrossed, label: 'Fiambres' },
  { key: 'ShoppingBag', Icon: ShoppingBag, label: 'Almacén' },
  { key: 'Gift', Icon: Gift, label: 'Varios' },
  { key: 'Shirt', Icon: Shirt, label: 'Ropa' },
  { key: 'Gem', Icon: Gem, label: 'Joyería' },
  { key: 'Tag', Icon: Tag, label: 'General' },
  { key: 'Package', Icon: Package, label: 'Otro' },
  // Fila 3: Tecnología, automotor y servicios
  { key: 'Laptop', Icon: Laptop, label: 'Computación' },
  { key: 'Smartphone', Icon: Smartphone, label: 'Celulares' },
  { key: 'Headphones', Icon: Headphones, label: 'Audio' },
  { key: 'Tv', Icon: Tv, label: 'Electrónica' },
  { key: 'Wrench', Icon: Wrench, label: 'Herramientas' },
  { key: 'Hammer', Icon: Hammer, label: 'Construcción' },
  { key: 'Zap', Icon: Zap, label: 'Electricidad' },
  { key: 'Car', Icon: Car, label: 'Automotor' },
  { key: 'Home', Icon: Home, label: 'Hogar' },
  { key: 'Armchair', Icon: Armchair, label: 'Muebles' },
  { key: 'Building2', Icon: Building2, label: 'Inmuebles' },
  { key: 'Store', Icon: Store, label: 'Comercio' },
  { key: 'Briefcase', Icon: Briefcase, label: 'Servicios' },
  { key: 'Camera', Icon: Camera, label: 'Fotografía' },
  // Fila 4: Salud, educación, arte y naturaleza
  { key: 'Scissors', Icon: Scissors, label: 'Peluquería' },
  { key: 'Stethoscope', Icon: Stethoscope, label: 'Salud' },
  { key: 'Dumbbell', Icon: Dumbbell, label: 'Deportes' },
  { key: 'Bike', Icon: Bike, label: 'Ciclismo' },
  { key: 'BookOpen', Icon: BookOpen, label: 'Libros' },
  { key: 'GraduationCap', Icon: GraduationCap, label: 'Educación' },
  { key: 'Printer', Icon: Printer, label: 'Oficina' },
  { key: 'Pencil', Icon: Pencil, label: 'Papelería' },
  { key: 'Music', Icon: Music, label: 'Música' },
  { key: 'Palette', Icon: Palette, label: 'Arte' },
  { key: 'Flame', Icon: Flame, label: 'Combustible' },
  { key: 'Trees', Icon: Trees, label: 'Jardín' },
  { key: 'Sun', Icon: Sun, label: 'Exterior' },
  { key: 'Pen', Icon: Pen, label: 'Librería' },
];

export const ICON_BY_KEY = Object.fromEntries(ICON_OPTIONS.map(o => [o.key, o.Icon]));

export const getCategoryIcon = (nombre, icono) => {
  if (icono && ICON_BY_KEY[icono]) return ICON_BY_KEY[icono];
  if (!nombre) return Package;
  const lower = nombre.toLowerCase();
  for (const { keys, Icon } of CATEGORY_ICON_MAP) {
    if (keys.some(k => lower.includes(k))) return Icon;
  }
  return Package;
};
